version: "3.9"
services:
  webserver:
    container_name: PHP-webserver
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.docker/apache:/etc/apache2/sites-enabled
      - ./www:/var/www/html/
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/php/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./.docker/php/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - 8000:80
      - 4430:443
    depends_on:
      - db
    networks:
      - dev-env

  # mysql-db:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: test_database
  #     MYSQL_USER: db_user
  #     MYSQL_PASSWORD: password
  #   ports:
  #     - "3306:3306"

  db:
    container_name: mariadb
    image: mariadb:latest
    volumes:
      - ./.docker/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: myP@ssw0rd
    ports:
      - 3306:3306
    networks:
      - dev-env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    volumes:
      - ./.docker/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    links:
      - db:db
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: admin
      PMA_PASSWORD: myP@ssw0rd
      UPLOAD_LIMIT: 20M
    ports:
      - 88:80
    networks:
      - dev-env

volumes:
  database: {}

networks:
  dev-env: {}
